#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 'α ' 'β ' 'γ ' 'δ ' 'ε ' 'ζ ' 'η ' 'θ ' 'ι '

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config top_padding 30

polibinput-gestures-setup startlybar &
nitrogen --set-scaled pictures/backpacker-7628303.jpg &
nitrogen --restore &
picom &

libinput-gestures-setup start
