[colors]
bg = #000000
fg = #f8f8f2
fg-alt = #9C9C9C

trans = #00000000
white = #FFFFFF
black = #000000

;; Material Colors
red = #e53935
pink = #d81b60
purple = #8e24aa
deep-purple = #5e35b1
indigo = #3949ab
blue = #1e88e5
light-blue = #039be5
cyan = #00acc1
teal = #00897b
green = #43a047
light-green = #7cb342
lime = #c0ca33
yellow = #fdd835
amber = #ffb300
orange = #fb8c00
deep-orange = #f4511e
brown = #6d4c41
grey = #757575
alpha-grey = #75757580
blue-gray = #546e7a

alert = ${colors.red}
accent = #604c7e


[global/wm]
margin-top = 0
margin-bottom = 34

[bar/main]
monitor = eDP
monitor-strict = true
enable-ipc = true
wm-restack = bspwm
# REQUIRED to move the window with hideit.sh
override-redirect = true
fixed-center = true

background = ${colors.bg}
foreground = ${colors.fg}

width = 100%
height = 34
offset-x = 0
offset-y = 0
top = true

; always-show = true

overline-size = 2
overline-color = #f00
underline-size = 2
underline-color = #00f

border-bottom-size = 0
border-top-size = 1
border-color = ${colors.bg-dark}

padding-left = 2
padding-right = 2
module-margin-left = 0
module-margin-right = 0

font-0 = "Jetbrains Mono:pixelsize=9;2"
font-1 = "Wuncon Siji:pixelsize=12;2"
font-2 = "Siji:pixelsize=10;2"

; modules-left = volume pad cpu memory pad pkg mail
modules-left = pulseaudio pad pad cpu pad memory pad fs
modules-center = bspwm
modules-right =  network-up pad wlan pad network-down pad pad battery pad date pad powermenu

tray-padding = 2
tray-transparent = true
tray-background = #0063ff

[module/bspwm]
type = internal/bspwm
pin-workspaces = true
enable-click = true

label-focused-format = <u><label-focused></u>
label-focused-underline = ${colors.accent}
format = <label-state> <label-mode> <label>
label-padding = 1

label-focused-background = ${colors.bg}
label-focused-line-size = 2
label-focused-foreground = ${colors.fg}
label-focused-padding = 1
format-focused = <label-focused>

label-occupied-foreground = ${colors.accent}
label-occupied-padding = 1

label-urgent-foreground = ${colors.alert}
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty-foreground = ${colors.fg-alt}
label-empty-padding = 1


[module/date]
type = internal/date
interval = 1

label = %date%  %time%
date = %A, %h %d
date-alt = %d/%m/%Y
time = %I:%M %p
time-alt = %H:%M:%S
format-prefix = "🖴"
format-prefix-padding = 1
format-prefix-foreground = ${colors.accent}

[module/fs]
type = internal/fs
mount-0 = /
interval = 30
format = <label-mounted>
label-padding = 1

label-mounted-foreground = ${colors.color4}
label-mounted-padding = 1

format-mounted-prefix = ""
format-mounted-prefix-foreground = ${colors.accent}

label-mounted = %used% / %total%

[module/cpu]
type = internal/cpu
interval = 3
format = <label>
label = %percentage%%
label-foreground = ${colors.color4}
label-padding = 1
format-prefix = ""
format-prefix-foreground = ${colors.accent}

[module/memory]
type = internal/memory
interval = 3
format = <label>
format-prefix = ""
format-prefix-foreground = ${colors.accent}

format-padding-left = 1
label-foreground = ${colors.color4}
label-padding = 1

[module/wlan]
type = internal/network
interface = wlan0
interval = 3.0

; name of the current network
label-connected = "%essid%"
label-connected-foreground = ${colors.fg}
format-connected = <label-connected>
; signal strength
format-connected-prefix-foreground = ${colors.accent}

format-disconnected =
format-disconnected-foreground =

ramp-signal-0 = 
ramp-signal-0-foreground = ${colors.yellow}
ramp-signal-1 = 
ramp-signal-1-foreground = ${colors.yellow}
ramp-signal-2 = 
ramp-signal-2-foreground = ${colors.yellow}
ramp-signal-3 = 
ramp-signal-3-foreground = ${colors.accent}
ramp-signal-4 = 
ramp-signal-4-foreground = ${colors.fg}

[module/network-up]
type = internal/network
interface = wlan0
interval = 4.0
label-connected = "%upspeed%"
format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.accent}
format-connected-foreground = ${colors.fg}
format-connected-background =
format-connected-underline =
format-disconnected-prefix = " "
format-disconnected-prefix-foreground = ${colors.alert}
format-disconnected-foreground = ${colors.alert}

[module/network-down]
type = internal/network
interface = wlan0
interval = 4.0
label-connected = "%downspeed%"
format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.accent}
format-connected-foreground = ${colors.fg}
format-connected-background =
format-connected-underline =
format-disconnected-prefix = " "
format-disconnected-prefix-foreground = ${colors.alert}
format-disconnected-foreground = ${colors.alert}


[module/pulseaudio]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>
format-muted = <label-muted>
format-muted-prefix = " "
format-muted-prefix-foreground = ${colors.alert}
format-muted-foreground = ${colors.alert}

label-volume = %percentage%%

label-muted = 


; Only applies if <ramp-volume> is used
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
full-at = 98
low-at = 20

format-charging = <animation-charging> <label-charging>
format-charging-underline = ${colors.accent}

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-underline =

format-full = <ramp-capacity> <label-full>
format-full-underline = ${colors.green}

format_low = <ramp-capacity> <label-low>
format_low-underline = ${colors.alert}

format-full-prefix-foreground = ${colors.fg-alt}

ramp-capacity-0 = ""
ramp-capacity-1 = ""
ramp-capacity-2 = ""
ramp-capacity-0-foreground = ${colors.red}
ramp-capacity-1-foreground = #575864
ramp-capacity-2-foreground = ${colors.fg-alt}

animation-charging-0 = ""
animation-charging-1 = ""
animation-charging-2 = ""
animation-charging-framerate = 1000
animation-charging-foreground = ${colors.fg-alt}

;=====================================================
; Custom scripts
;=====================================================

[module/pad]
type = custom/text
content = "   "
content-foreground = ${colors.fg-alt}

; vim:ft=dosini
